import React from "react";
import { Navbar, Nav, NavItem, NavDropdown, MenuItem } from "react-bootstrap";
import "bootstrap/dist/css/bootstrap.css";
import "bootstrap/dist/css/bootstrap-theme.css";

const NavBar = () => {
  return (<div>
    <nav class = "navbar navbar-inverse" >
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">IMGHOST</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">New Post <span class="sr-only">(current)</span></a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
          <form class="navbar-form navbar-left">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search" />
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
            <li><a href="#">Sign Up</a></li>
            <li><a href="#">Sign In</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <h1>http://jossmac.github.io/react-images/</h1>
    <nav class="navbar navbar-default navbar-fixed-bottom">
      <div class="container">
        <span class="label label-default">Cats</span>
        <span class="label label-primary">Dogs</span>
        <span class="label label-success">Nature</span>
        <span class="label label-info">Funny</span>
        <span class="label label-warning">Cars</span>
        <span class="label label-danger">Travel</span>
        <h5>Make a bunch of tags(max them out at the top 100 tags) that are generated by the users tagging the public photos.</h5>
        <p>When a tag is clicked on it should filter the photos to only display those photos that have that tag</p>
        <p>can we resize tag based on number of photos? like if it has 1000+ related photos it is v large and if it only has 30 it is way smaller? </p>
      </div>
    </nav>
  </div>
  );
};

export default NavBar;